---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./local-path-provisioner-repository.yaml
  - ./kong-repository.yaml
  - ./jetstack-repository.yaml
  - ./tf-controller-repository.yaml