---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-nginx-aggregator
resources:
  - ../base/ingress-nginx/ingress-release.yaml
  - ../base/ingress-nginx/ingress-namespace.yaml