---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./node-config.yaml
  - ../base/namespaces
  - ../base/sources
  - ./kong-gateway.yaml
  - ./cert-manager.yaml
  - ./tf-controller.yaml