---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/namespaces
  - ../base/sources
  - ./metallb-controller.yaml
  - ./metallb-config.yaml
  - ./ingress-nginx.yaml