---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/sources/helm-sources.yaml
  - ../base/metallb/metallb-namespace.yaml
  - ./metallb-kustomization.yaml
  - ./ingress-nginx-kustomization.yaml