---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metallb-kustomization-aggregator
resources:
  - ../base/metallb/metallb-release.yaml
  - ../base/metallb/metallb-config.yaml