---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-config
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/node-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true